### ISSUE TITLE
bump npm version

### ISSUE THREAD

**Issue by Offirmo** [hrishikeshs/json-htmlize#6]
Your module looks nice and may fit my need.

However, it seems the npm version is not up to date.

Just in case : `npm publish` must be called each time you want to bump the version.
```
npm version patch
git commit
git push
git push --tags
npm publish
```

**Comment by hrishikeshs** [comment]
Hi @Offirmo , nice to hear that you found my module useful, I haven't bumped the version yet because the api has changed a little: you now get a dom node instead of the string, I will bump version once I update the documentation.

**Comment by Offirmo** [comment]
Hey hey hey I'm using your module to send an html report email from my node app. The html as a string is great for that. Will I be able to do that with the new API ?

**Comment by hrishikeshs** [comment]
@Offirmo Oh,  I hadn't thought of that use-case. Maybe it's more common than what I had originally planned. Let me revert the commit which I made on master.

**Comment by hrishikeshs** [comment]
@Offirmo, one question: Are you using the module to generate the html string and doing a `innerHTML=` somewhere?

**Comment by Offirmo** [comment]
@hrishikeshs nope. Code looks like that :

```javascript
var msg = 'Just to let you know.<br />\n' + htmlize(rapport.base);

mandrill('/messages/send', {
  message: {
    to: [
      {email: config.admin_email, name: 'online-adventur.es admin'}
    ],
    from_email: config.agent_email,
    subject: subject,
    html: start_msg,    // <-- here, HTML as a string
  }
}, function (error, responses) {
...
```

**Comment by hrishikeshs** [comment]
@Offirmo You will still be able to use the generated dom as a html string. It's quite easy, all you need to do is, to get the `innerHTML` of the dom my module generates. However, please be careful when you stick it into your page, you might have to html-escape it. Even with the older api, you would have to html-escape the output though.

**Comment by hrishikeshs** [comment]
so an example for this might be:
```
var q = toHtml({"name" : "mongo", "type" : "db"});
console.log(q);
```
prints out
```
"<span>{</span><div style="margin-left: 30px;"><strong>name:  </strong><span>mongo</span>,</div><div style="margin-left: 30px;"><strong>type:  </strong><span>db</span></div><span>}</span>"
```

**Comment by Offirmo** [comment]
@hrishikeshs can't you provide both a `.toHtmlAsDom` and a `.toHtmlAsString` ? That would be so convenient...

**Comment by hrishikeshs** [comment]
@Offirmo I could do that. It's pretty straightforward to do. I'll do that after dinner maybe :smile:

**Comment by hrishikeshs** [comment]
@Offirmo I've exposed the api, but haven't  bumped the version yet.

**Comment by Offirmo** [comment]
@hrishikeshs man, you're great !

**Comment by hrishikeshs** [comment]
@Offirmo, published to npm, closing this issue.
